### ISSUE TITLE
Feature request: base class for event args

### ISSUE THREAD

**Issue by grokky1** [StephenClearyArchive/AsyncEx.Oop#1]
Many (in my experience, most) event handlers use event args without data. So this is boilerplate:

    public class AsyncEventArgs : EventArgs, IDeferralSource
    {
      internal DeferralManager DeferralManager { get; } = new DeferralManager();
      public IDisposable GetDeferral() => DeferralManager.DeferralSource.GetDeferral();
    }

So would you kindly consider adding it to the library? Would make calling code mush cleaner.

If someone needs eventargs with data, then just subclass `AsyncEventArgs`. Which would also be cleaner.

**Comment by StephenCleary** [comment]
Yes, absolutely! I just read a blog post last week where someone used a base class for this, and thought it would be a good idea.

The only real question is how the `internal` member should be exposed. Possibly keep it `internal` and just add event-raising helpers...

**Comment by grokky1** [comment]
Good point, I didn't think about that! Internal and helpers, probably, but I'm not sure.

I always prefer to hide things away at first, and expose them later if I need to.

**Comment by StephenCleary** [comment]
This issue was moved to StephenCleary/AsyncEx#87
